If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [11]:
def sum_mult_3_5(num_limit):
    mult = []
    for x in range(1,num_limit):
        if x%3 == 0 or x%5 == 0:
            mult.append(x)
    return sum(mult)

In [12]:
sum_mult_3_5(10)

23

In [13]:
sum_mult_3_5(1000)

233168

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [28]:
def fib(num_limit):
    a=0
    b=1
    seq = []
    if num_limit == 0:
        return seq
    if num_limit == 1:
        seq.append(b)
        return seq
    else:
        for x in range(num_limit):
            c = a+b
            if c < 4000000:
                a=b
                b=c
                if c%2 == 0:
                    seq.append(c)
            else:
                break
    return sum(seq)

In [30]:
fib(2000)

4613732

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [51]:
def primeFactor(num):
    pf = []
    for i in range(2,num):
        if num%i == 0:
            divisible = False
            for j in pf:
                if i%j == 0:
                    divisible = True
                    break
            if divisible == False:
                pf.append(i)
            else:
                break
    return max(pf)

In [53]:
primeFactor(600851475143)

6857

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [59]:
a = 909
b = str(a)
b[::-1]

'909'

In [64]:
def palindrome(lower,upper):
    pal = []
    for i in range(lower,upper):
        for j in range(i,upper):
            prod = i*j
            if str(prod) == str(prod)[::-1]:
                pal.append(prod)
    return max(pal)
                
palindrome(100,1000)

906609

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [86]:
def evenly_divisible(max_num):
    
    for i in range(1,max_num):
        ed = True
        for j in range(1,21):
            if i%j != 0:
                ed = False
                break
        if ed == True:
            return i
            break
            
evenly_divisible(250000000)

232792560

In [85]:

import numpy

ints = numpy.array(range(1,21))
primes = [2,3,5,7,11,13,17,19] # under 20
facts = []
for p in primes:
    counter = 0
    nums = ints
    while any(nums % p == 0):
        nums = nums / float(p)
        counter += 1
    facts.append(counter)

facts = numpy.array(facts)
mults = primes**facts
ans = 1
for m in mults:
    ans = m * ans

print(ans)

232792560

In [90]:
def prob5():
    i=20
    while 1:
        i+=20
        if i%11==0 and i%12==0 and i%13==0 and \
        i%14==0 and i%15==0 and i%16==0 and \
        i%17==0 and i%18==0 and i%19== 0:
                print(i)
                break

In [91]:
prob5()

232792560

The sum of the squares of the first ten natural numbers is,

12 + 22 + ... + 102 = 385
The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [96]:
def sum_squares_minus_square_sum(num_limit):
    square_sum = 0
    sum_square = 0
    for i in range(1,num_limit+1):
        square_sum = square_sum + i**2
        sum_square = sum_square + i
    
    return (sum_square)**2 - square_sum

In [98]:
sum_squares_minus_square_sum(100)

25164150

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [155]:
def four_adj_digit_max_product(num_digits):
    num = 7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450
    max_prod = 0
    n = [int(x) for x in str(num)]   
    max_list = []
    
    for i in range(0,len(str(num))-num_digits-1):
        sum_prod = 1
        dig_list = []
        for j in range(0,num_digits):
            dig_list.append(n[j+i])
            sum_prod *= n[j+i]
            if sum_prod > max_prod:
                max_prod = sum_prod
                max_list = dig_list
        
    
    print(max_prod)
    print(max_list)

In [156]:
four_adj_digit_max_product(13)

23514624000
[5, 5, 7, 6, 6, 8, 9, 6, 6, 4, 8, 9, 5]

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [165]:
from math import sqrt

def pythog_trip(max_num):
    trip = []
    for i in range(1,max_num):
        for j in range(i+1,max_num):
            if float.is_integer(sqrt(i**2 + j**2)) and i+j+sqrt(i**2 + j**2) == 1000:
                trip.append(i)
                trip.append(j)
                trip.append(sqrt(i**2 + j**2))
    print(trip)

In [168]:
pythog_trip(500)

[200, 375, 425.0]

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [178]:
def is_prime(a):
    return all(a % i for i in range(2, a))


def sum_primes(below_num):
    sum_prime = 0
    for i in range(2,below_num):
        if is_prime(i):
            sum_prime += i
    
    return sum_prime

In [186]:
sum = 2

def isPrime(n):
    if n % 2 == 0: return False
    for i in range(3, int(n**0.5)+1, 2):
        if n % i == 0: return False
    return True
if __name__ == "__main__":
    n = 1
    while n < 2000000:
        n += 2
        if isPrime(n):sum += n
print(sum)

142913828922